### ISSUE TITLE
Add support for versioned secret keys

### ISSUE THREAD

**Issue by ramizpolic** [bank-vaults/secret-sync#4]
## Idea
We would like to have versioned API operations (fetching/querying/updating) on supported providers, as well as secret key version rewrites.

## Strategy
All implementations of `StoreClient` should take into account `SecretKey.Version` field.
Additionally, `RegexpRewrite` should be extended to allow specifying which `SecretKey` field to rewrite, for example:
```
type RegexpRewrite struct {
	Field string `json:"field"` // make this an enum with values: "Key", "Version"
	Source string `json:"source"`
	Target string `json:"target"`
}
```

## Acceptance criteria
Running the following sync plan will:
1) Sync secret `a` with version `3`
2) Sync all secrets with version `2` for path `d/d/d`
3) Sync secret `a` with version `5` into secret `a` with version `6`
```yaml
plan:
  - secret:
      key: "a"
      version: "3"
  - query:
      path: "d/d/d"
      key:
        regexp: .*
      version:
        regexp: "2"
  - secret:
      key: "a"
      version: "5"
    rewrite:
      - regexp:
          field: "Key"
          source: "a" # key queries are executed on Key only
          target: "b"
      - regexp:
          field: "Version"
          source: ".*#5" # versioned queries are executed on Key#Version
          target: "6"
```

This needs to be discussed with the rest of the team.
Feel free to suggest a better implementation plan.
